/*
 * FairOS-dfs server
 *
 * A list of the currently provided Interfaces to interact with FairOS decentralised file system(dfs), implementing user, pod, file system, key value store and document store
 *
 * API version: v0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type DirStats struct {
	AccessTime string `json:"accessTime,omitempty"`
	CreationTime string `json:"creationTime,omitempty"`
	DirName string `json:"dirName,omitempty"`
	DirPath string `json:"dirPath,omitempty"`
	Mode int32 `json:"mode,omitempty"`
	ModificationTime string `json:"modificationTime,omitempty"`
	NoOfDirectories string `json:"noOfDirectories,omitempty"`
	NoOfFiles string `json:"noOfFiles,omitempty"`
	PodName string `json:"podName,omitempty"`
}
