/*
 * FairOS-dfs server
 *
 * A list of the currently provided Interfaces to interact with FairOS decentralised file system(dfs), implementing user, pod, file system, key value store and document store
 *
 * API version: v0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type FileStats struct {
	AccessTime string `json:"accessTime,omitempty"`
	BlockSize string `json:"blockSize,omitempty"`
	Compression string `json:"compression,omitempty"`
	ContentType string `json:"contentType,omitempty"`
	CreationTime string `json:"creationTime,omitempty"`
	FileName string `json:"fileName,omitempty"`
	FilePath string `json:"filePath,omitempty"`
	FileSize string `json:"fileSize,omitempty"`
	Mode int32 `json:"mode,omitempty"`
	ModificationTime string `json:"modificationTime,omitempty"`
	PodName string `json:"podName,omitempty"`
}
