/*
 * FairOS-dfs server
 *
 * A list of the currently provided Interfaces to interact with FairOS decentralised file system(dfs), implementing user, pod, file system, key value store and document store
 *
 * API version: v0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type UserReceiveFileInfo struct {
	BlockSize string `json:"blockSize,omitempty"`
	Compression string `json:"compression,omitempty"`
	ContentType string `json:"contentType,omitempty"`
	DestAddress string `json:"destAddress,omitempty"`
	Name string `json:"name,omitempty"`
	NumberOfBlocks string `json:"numberOfBlocks,omitempty"`
	SharedTime string `json:"sharedTime,omitempty"`
	Size string `json:"size,omitempty"`
	SourceAddress string `json:"sourceAddress,omitempty"`
}
